# Generated by Django 4.2.1 on 2023-06-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skuadra_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Futbollisti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('futbollisti_id', models.IntegerField(unique=True)),
                ('skuadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.skuadra')),
            ],
        ),
    ]
