# Generated by Django 4.2.1 on 2023-06-14 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_skuadra_futbollisti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futbollisti',
            name='futbollisti_id',
        ),
        migrations.RemoveField(
            model_name='futbollisti',
            name='skuadra',
        ),
        migrations.AddField(
            model_name='futbollisti',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futbollisti',
            name='team',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
