# Generated by Django 4.1.5 on 2023-06-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_futbollisti_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbollisti',
            name='team',
            field=models.CharField(max_length=100),
        ),
    ]
