# Generated by Django 4.1.5 on 2023-06-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_futbollisti_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbollisti',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.skuadra'),
        ),
    ]
